SimpleSchema.messages({
  required: "[label] хэрэгтэй",
  minString: "[label] доод тал нь [min] тэмдэгттэй байх ёстой",
  maxString: "[label] дээд тал нь [max] тэмдэгттэй байх ёстой",
  minNumber: "[label] доод тал нь [min] байх ёстой",
  maxNumber: "[label] дээд тал нь [max] байх ёстой",
  minDate: "[label] нь [min] эсвэл үүнээс хойш байх ёстой",
  maxDate: "[label] нь [max]-с хойш байж болохгүй",
  badDate: "[label] нь зөв огноо биш байна",
  minCount: "Доод тал нь [minCount] утга тодорхойлох ёстой",
  maxCount: "Дээд тал нь [maxCount] утга тодорхойлох ёстой",
  noDecimal: "[label] нь бүхэл тоо байх ёстой",
  notAllowed: "[value] нь зөвшөөрөгдөөгүй утга байна",
  expectedString: "[label] нь тэмдэгт мөр байх ёстой",
  expectedNumber: "[label] нь тоо байх ёстой",
  expectedBoolean: "[label] нь boolean байх ёстой",
  expectedArray: "[label] нь Array байх ёстой",
  expectedObject: "[label] нь Object байх ёстой",
  expectedConstructor: "[label] нь [type] байх ёстой",
  regEx: [
    {msg: "[label] нь regular expression шалгалтыг давж чадсангүй"},
    {exp: SimpleSchema.RegEx.Email, msg: "[label] нь зөв имэйл хаяг байх ёстой"},
    {exp: SimpleSchema.RegEx.WeakEmail, msg: "[label] нь зөв имэйл хаяг байх ёстой"},
    {exp: SimpleSchema.RegEx.Domain, msg: "[label] нь зөв домэйн хаяг байх ёстой"},
    {exp: SimpleSchema.RegEx.WeakDomain, msg: "[label] нь зөв домэйн хаяг байх ёстой"},
    {exp: SimpleSchema.RegEx.IP, msg: "[label] нь зөв IPv4 эсвэл IPv6 хаяг байх ёстой"},
    {exp: SimpleSchema.RegEx.IPv4, msg: "[label] нь зөв IPv4 хаяг байх ёстой"},
    {exp: SimpleSchema.RegEx.IPv6, msg: "[label] нь зөв IPv6 хаяг байх ёстой"},
    {exp: SimpleSchema.RegEx.Url, msg: "[label] нь зөв URL байх ёстой"},
    {exp: SimpleSchema.RegEx.Id, msg: "[label] нь зөв үсэг, тоо оролцсон ID байх ёстой"}
  ],
  keyNotInSchema: "[key] нь schema-д зөвшөөрөгдөхгүй байна"
});
